// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXMhMq8rijy0ELmoh7fUxQnjq7_Gdv-CU',
    appId: '1:211376122752:web:4b68044bed60a047faef65',
    messagingSenderId: '211376122752',
    projectId: 'test-a6e0e',
    authDomain: 'test-a6e0e.firebaseapp.com',
    storageBucket: 'test-a6e0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP5-oyint55cCoFC7gy3V5kUbbUiFcjk4',
    appId: '1:211376122752:android:72a4d94c41e13057faef65',
    messagingSenderId: '211376122752',
    projectId: 'test-a6e0e',
    storageBucket: 'test-a6e0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOKIr3vfGD6WCZvCg6TL6EivHHrzjvU7I',
    appId: '1:211376122752:ios:86350bda273e3319faef65',
    messagingSenderId: '211376122752',
    projectId: 'test-a6e0e',
    storageBucket: 'test-a6e0e.appspot.com',
    iosBundleId: 'com.example.paginationApplicatoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOKIr3vfGD6WCZvCg6TL6EivHHrzjvU7I',
    appId: '1:211376122752:ios:86350bda273e3319faef65',
    messagingSenderId: '211376122752',
    projectId: 'test-a6e0e',
    storageBucket: 'test-a6e0e.appspot.com',
    iosBundleId: 'com.example.paginationApplicatoin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXMhMq8rijy0ELmoh7fUxQnjq7_Gdv-CU',
    appId: '1:211376122752:web:a6c5dea0d5f4cc1efaef65',
    messagingSenderId: '211376122752',
    projectId: 'test-a6e0e',
    authDomain: 'test-a6e0e.firebaseapp.com',
    storageBucket: 'test-a6e0e.appspot.com',
  );
}
